# Generated by Django 5.1.5 on 2025-01-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("tv", "TV"),
                            ("laptop", "Laptop"),
                            ("smartwatch", "Smartwatch"),
                            ("accessory", "Accessory"),
                        ],
                        default="mobile",
                        max_length=50,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="BrandOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(help_text="Title of the brand", max_length=100),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discount percentage or offer",
                        max_digits=10,
                    ),
                ),
                ("description", models.TextField(help_text="Description of the offer")),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Product_Cards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Slideshow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Default title",
                        help_text="Title of the image",
                        max_length=100,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        default="Default caption",
                        help_text="Caption for the image",
                        max_length=255,
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which the image should appear"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
