# Generated by Django 5.1.5 on 2025-01-29 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myecommerce_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobiles",
                        to="myecommerce_app.brand",
                    ),
                ),
            ],
        ),
    ]
