# Generated by Django 5.1.5 on 2025-01-29 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myecommerce_app", "0002_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="category",
            field=models.CharField(
                choices=[
                    ("mobiles", "Mobiles"),
                    ("tablet", "Tablet"),
                    ("tv", "TV"),
                    ("laptop", "Laptop"),
                    ("smartwatch", "Smartwatch"),
                    ("accessory", "Accessory"),
                ],
                default="mobile",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mobile",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mobile",
                to="myecommerce_app.brand",
            ),
        ),
    ]
