# Generated by Django 5.1.5 on 2025-01-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myecommerce_app", "0003_alter_brand_category_alter_mobile_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="category",
            field=models.CharField(
                choices=[
                    ("mobiles", "Mobiles"),
                    ("tablet", "Tablet"),
                    ("tv", "TV"),
                    ("laptop", "Laptop"),
                    ("smartwatch", "Smartwatch"),
                    ("accessory", "Accessory"),
                ],
                default="mobiles",
                max_length=50,
            ),
        ),
    ]
