# Generated by Django 5.1.5 on 2025-01-29 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myecommerce_app", "0004_alter_brand_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobile",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mobiles",
                to="myecommerce_app.brand",
            ),
        ),
    ]
