# Generated by Django 5.1.5 on 2025-01-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myecommerce_app", "0007_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobile",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Mobile",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
