# Generated by Django 5.1.5 on 2025-02-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myecommerce_app", "0008_remove_mobile_brand_remove_product_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="card_expiry",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="card_number",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cvv",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit-card", "Credit Card"),
                    ("upi", "UPI"),
                    ("cash-on-delivery", "Cash on Delivery"),
                ],
                default="cash-on-delivery",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default="Not Provided", max_length=15),
        ),
    ]
