# Generated by Django 5.1.5 on 2025-02-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("myecommerce_app", "0010_customuser"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="Login_user_accounts",
        ),
    ]
