# Generated by Django 5.1.5 on 2025-02-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myecommerce_app", "0012_alter_login_user_accounts_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login_user_accounts",
            name="password",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
