# Generated by Django 5.1.5 on 2025-02-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce_app', '0013_alter_login_user_accounts_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_user_accounts',
        ),
    ]
