# Generated by Django 5.1.5 on 2025-02-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myecommerce_app", "0014_delete_login_user_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
