# Generated by Django 5.1.5 on 2025-02-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce_app', '0016_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
