# Generated by Django 5.1.5 on 2025-02-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myecommerce_app", "0017_alter_userprofile_profile_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
