# Generated by Django 5.1.5 on 2025-02-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce_app', '0018_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comingsoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/commingsoon/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
