# Generated by Django 5.1.5 on 2025-02-10 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myecommerce_app", "0019_comingsoon"),
    ]

    operations = [
        migrations.AddField(
            model_name="comingsoon",
            name="name",
            field=models.CharField(default="Coming Soon Item", max_length=100),
        ),
        migrations.AddField(
            model_name="comingsoon",
            name="release_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="comingsoon",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
