# Generated by Django 5.1.5 on 2025-02-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myecommerce_app", "0025_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="state_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_state",
                to="myecommerce_app.contact",
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="country_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_country",
                to="myecommerce_app.contact",
            ),
        ),
    ]
