# Generated by Django 5.1.5 on 2025-02-15 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce_app', '0026_contactus_state_name_alter_contactus_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='myecommerce_app.contact')),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_state', to='myecommerce_app.state'),
        ),
    ]
